name: Scraping Diario

on:
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC
  workflow_dispatch:      # También permite ejecutarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install selenium pandas

      - name: Ejecutar scraping
        run: python scrapersbs.py
