name: Scraping Manual

on:
  workflow_dispatch:
    inputs:
      fecha_inicio:
        description: 'Fecha inicio (dd/mm/yyyy)'
        required: true
      fecha_fin:
        description: 'Fecha fin (dd/mm/yyyy)'
        required: true

jobs:
  run-manual-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Ejecutar script iterativo con fechas
        env:
          FECHA_INICIO: ${{ github.event.inputs.fecha_inicio }}
          FECHA_FIN: ${{ github.event.inputs.fecha_fin }}
        run: python run_manual_scraper.py
